CREATE DATABASE JT_ARTICULOS

CREATE TABLE Articuloscientificos (
    Id INT PRIMARY KEY IDENTITY,
    Titulo NVARCHAR(200) NOT NULL,
    FechaPublicacion DATE,
    Descripcion NVARCHAR(500) NOT NULL,
    Autor NVARCHAR(200) NOT NULL,
    FechaRegistro DATETIME DEFAULT CURRENT_TIMESTAMP,
);